spring.application.name=cadance

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http.client=DEBUG

spring.security.oauth2.client.registration.strava.client-id=${STRAVA_CLIENT_ID}
spring.security.oauth2.client.registration.strava.client-secret=${STRAVA_CLIENT_SECRET}
spring.security.oauth2.client.registration.strava.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.strava.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.strava.redirect-uri={baseUrl}/login/oauth2/code/strava
spring.security.oauth2.client.registration.strava.scope=activity:read_all

spring.security.oauth2.client.provider.strava.authorization-uri=https://www.strava.com/oauth/authorize
spring.security.oauth2.client.provider.strava.token-uri=https://www.strava.com/oauth/token
spring.security.oauth2.client.provider.strava.user-info-uri=https://www.strava.com/api/v3/athlete
spring.security.oauth2.client.provider.strava.user-name-attribute=id
